name: CI for Backend (Flask, SQLAlchemy, PostgreSQL)

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  Backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r Backend/requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/Backend" >> $GITHUB_ENV
      
      - name: Set OpenAI API Key
        run: export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

      - name: Run tests
        run: |
          source env/bin/activate
          python3.11 -m unittest discover -s Backend/tests/server_tests